outFile=input("Enter the name of the desired output file:")
file = open(outFile,"w")
userInput = input("Enter a space-seperated [Position] coordinates of the camera: ")
file.write("{}\n".format(userInput))
userInput = input("Enter a space-seperated coordinates representing the [Gaze] vector: ")
file.write("{}\n".format(userInput))
userInput = input("Enter a space-seperated coordinates representing [V] vector: ")
file.write("{}\n".format(userInput))
userInput = input("Enter a space-seperated [l r b t sizeX sizeY] ")
file.write("{}\n".format(userInput))
userInput = input("Enter the name of the output image file:")
file.write("{}\n".format(userInput))

print("File '{}' has been generated successfully.".format(outFile))
